image: ubuntu:latest

deploy:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://172.17.0.1:2375
    PROJECT_NAME: gateway
    TAG: latest
  before_script:
    - docker login -u ${DOCKER_IO_USER} -p ${DOCKER_IO_TOKEN}
  after_script:
    - docker logout
  script:
    - docker build --file Dockerfile -t ${DOCKER_IO_USER}/${PROJECT_NAME}:$TAG . --no-cache
    - docker push ${DOCKER_IO_USER}/${PROJECT_NAME}:$TAG
