version: '3.8'
services:
  gateway:
    image: laszlo/gateway:latest
    container_name: gateway
    ports:
      - 2222:22
    volumes:
      - path/to/your/directory:/home/laszlo
    environment:
      - USER_ID=999
      - USERNAME=laszlo
      - PASSWORD=password
...
